const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const fmt = (n) => new Intl.NumberFormat('zh-CN').format(n);
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeUrl = (value) => /^https?:\/\//i.test(String(value || '')) ? esc(value) : '#';
const skillZh = {Listening:'听力',Speaking:'口语',Reading:'阅读',Writing:'写作'};
const groupZh = {official_public:'官方公开材料',cambridge_derived:'剑桥派生词汇',test_taker_recall:'考生回忆',public_compilation:'公开非官方汇编',user_provided:'用户提供材料',third_party_prediction:'第三方预测题'};
const confidenceZh = {high:'高',medium:'中',exploratory:'探索'};
const labelZh = {'agree-disagree/opinion':'同意/不同意（观点题）','discuss-both-views':'讨论双方观点','advantages-disadvantages/outweigh':'优缺点 / 是否利大于弊','problem-solution/causes-effects':'原因·影响·解决方案','causes-problems-solutions':'原因与解决方案','two-part/direct questions':'双问题 / 直接问答','positive-negative development':'积极或消极发展','line/trend':'折线与趋势','bar/column':'柱状图','pie/proportion':'饼图与比例',table:'表格','map/plan':'地图与平面变化',process:'流程图','mixed/multiple visuals':'混合图','diagram/system/other':'示意图 / 系统图 / 其他',education:'教育','children-family':'儿童与家庭','work-economy':'工作与经济','government-public-policy':'政府与公共政策','society-culture':'社会与文化','technology-media':'科技与媒体','environment-energy':'环境与能源','transport-cities-housing':'交通·城市·住房','health-lifestyle':'健康与生活方式','globalization-travel':'全球化与旅行','arts-sports':'艺术与体育','crime-law':'犯罪与法律','science-research-language':'科学·研究·语言',health:'健康',crime:'犯罪',other:'其他'};
const speakingThemeZh = {'person/family/friends':'人物·家庭·朋友','object/technology':'物品·科技','travel-transport':'旅行·交通',place:'地点','home/hometown/accommodation':'家·家乡·居住','event/experience':'事件·经历',food:'食物·饮食','activity/hobby':'活动·爱好','society-government':'社会·公共事务','work-study':'学习·工作',culture:'文化·传统',other:'日常·综合'};
let data;
let speakingData;
let questionBank;
let writingBank;
let chunkBank;
let manifest;
let activeTopicId='';
let expandedTopicId='';
let dialogMode='practice';
let sourceViewState={part:'',current:false,q:'',limit:40};
let wordState = {skill:'Reading',scope:'overall',q:'',page:1};
let topicState = {part:'',current:true,q:'',page:1};
let writingState = {task:'Task 1',expanded:'',mode:'analysis'};
let chunkState = {skill:'Reading',category:'全部',expanded:''};

function tags(groups){return `<div class="tags">${groups.map(g=>`<span>${esc(groupZh[g]||g)}</span>`).join('')}</div>`}
function showView(){const view=(location.hash.slice(1)||'home').split('?')[0];$$('.view').forEach(el=>el.hidden=el.dataset.view!==view);scrollTo({top:0,behavior:'instant'});}
function buttonTabs(el, items, current, callback){el.innerHTML=items.map(([v,l])=>`<button class="${v===current?'active':''}" data-value="${v}">${l}</button>`).join('');el.querySelectorAll('button').forEach(b=>b.onclick=()=>callback(b.dataset.value));}
function pager(el,page,total,size,callback){const pages=Math.max(1,Math.ceil(total/size));el.innerHTML=`<button ${page===1?'disabled':''} data-d="-1">上一页</button><span>第 ${page} / ${pages} 页</span><button ${page>=pages?'disabled':''} data-d="1">下一页</button>`;el.querySelectorAll('button').forEach(b=>b.onclick=()=>callback(page+Number(b.dataset.d)));}

function renderHome(){
  $('#hero-stats').innerHTML=`<span><b>${fmt(data.meta.documentCount)}</b>统计单元</span><span><b>${fmt(data.meta.filteredTokenCount)}</b>学习词 token</span><span><b>${fmt(speakingData.meta.mergedTopicCount)}</b>口语合并主题</span><span><b>${fmt(questionBank.meta.practiceQuestionCount)}</b>口语练习问答</span><span><b>${fmt(writingBank.meta.exerciseCount)}</b>写作题目与原创范文</span>`;
  $('#home-coverage').innerHTML=data.coverage.map(r=>`<article class="metric"><strong>${fmt(r.documents)}</strong><h3>${skillZh[r.skill]}</h3><p>${fmt(r.filteredTokens)} 个学习词 token · ${r.sources} 个来源集合</p>${tags(r.sourceGroups)}</article>`).join('');
  $('#hero-search').onsubmit=e=>{e.preventDefault();wordState.q=new FormData(e.target).get('q').trim();wordState.page=1;location.hash='words';renderWords()};
}
function renderWords(){
  buttonTabs($('#skill-tabs'),Object.entries(skillZh),wordState.skill,v=>{wordState.skill=v;wordState.page=1;renderWords()});
  buttonTabs($('#scope-tabs'),[['overall','总体'],['recent_5y','近五年']],wordState.scope,v=>{wordState.scope=v;wordState.page=1;renderWords()});
  $('#word-search input').value=wordState.q;$('#word-search').onsubmit=e=>{e.preventDefault();wordState.q=e.target.querySelector('input').value.trim().toLowerCase();wordState.page=1;renderWords()};
  const all=data.words.filter(r=>r.skill===wordState.skill&&r.scope===wordState.scope&&(!wordState.q||r.lemma.includes(wordState.q)));const rows=all.slice((wordState.page-1)*50,wordState.page*50);
  $('#word-note').textContent=`共 ${fmt(all.length)} 个达到最低文档频次的学习词`;
  $('#word-body').innerHTML=rows.map(r=>`<tr><td><span class="rank">#${r.rank}</span><b>${esc(r.display)}</b></td><td>${fmt(r.occurrenceCount)}</td><td>${fmt(r.documentFrequency)} <small>(${(r.documentCoverage*100).toFixed(1)}%)</small></td><td>${r.normalizedPer10k.toFixed(2)}</td><td>${r.sourceCount}</td><td><span class="badge ${esc(r.confidence)}">${esc(confidenceZh[r.confidence])}</span></td></tr>`).join('')||'<tr><td colspan="6">没有匹配的词。</td></tr>';
  pager($('#word-pages'),wordState.page,all.length,50,p=>{wordState.page=p;renderWords()});
}
function clearTopicHover(){
  const grid=$('#topic-grid');if(!grid)return;grid.querySelectorAll('.topic.hover-main,.topic.hover-peer').forEach(card=>{card.classList.remove('hover-main','hover-peer');card.style.removeProperty('flex-basis')});
}
function setupTopicHover(){
  const grid=$('#topic-grid');if(!grid||!matchMedia('(hover: hover) and (pointer: fine)').matches)return;
  grid.onpointerleave=clearTopicHover;
  grid.querySelectorAll('.topic').forEach(card=>card.onpointerenter=()=>{
    if(expandedTopicId)return;clearTopicHover();
    const cards=[...grid.querySelectorAll('.topic')];const columns=matchMedia('(max-width: 640px)').matches?1:matchMedia('(max-width: 980px)').matches?2:3;const index=cards.indexOf(card);const rowStart=Math.floor(index/columns)*columns;const row=cards.slice(rowStart,rowStart+columns);if(row.length<2)return;
    const gap=parseFloat(getComputedStyle(grid).columnGap)||14;const available=grid.clientWidth-gap*(row.length-1)-4;const mainRatio=row.length>=3?.46:.62;const mainWidth=available*mainRatio;const peerWidth=(available-mainWidth)/(row.length-1);
    row.forEach(item=>{const main=item===card;item.classList.add(main?'hover-main':'hover-peer');item.style.flexBasis=`${main?mainWidth:peerWidth}px`});
  });
}
function renderTopics(){
  buttonTabs($('#part-tabs'),[['','全部 Part'],['Part 1','Part 1'],['Part 2','Part 2'],['Part 3','Part 3']],topicState.part,v=>{expandedTopicId='';activeTopicId='';topicState.part=v;topicState.page=1;renderTopics()});
  $('#current-only').checked=topicState.current;$('#current-only').onchange=e=>{expandedTopicId='';activeTopicId='';topicState.current=e.target.checked;topicState.page=1;renderTopics()};$('#topic-search input').value=topicState.q;$('#topic-search').onsubmit=e=>{e.preventDefault();expandedTopicId='';activeTopicId='';topicState.q=e.target.querySelector('input').value.trim().toLowerCase();topicState.page=1;renderTopics()};
  const all=speakingData.topics.filter(r=>(!topicState.part||r.parts.includes(topicState.part))&&(!topicState.current||(topicState.part?r.questions.some(question=>question.part===topicState.part&&question.current):r.current))&&(!topicState.q||r.title.toLowerCase().includes(topicState.q)||r.titleZh.includes(topicState.q)||r.aliases.some(alias=>alias.toLowerCase().includes(topicState.q))));const rows=all.slice((topicState.page-1)*36,topicState.page*36);
  $('#topic-note').textContent=`匹配 ${fmt(all.length)} 个合并主题；${topicState.part||'全部 Part'} 只展示对应的准备题，来源材料放在展开后的参考区。`;
  $('#topic-grid').innerHTML=rows.map(r=>{const practice=questionBank.topics[r.id];const prepared=(practice?.questions||[]).filter(question=>!topicState.part||question.part===topicState.part);const aliasText=r.aliases.slice(0,3).join(' · ');const partLabel=topicState.part||r.partStructure;return `<article class="topic" data-topic-id="${esc(r.id)}"><div class="topic-meta"><span>${esc(r.titleZh)}</span><span>${esc(partLabel)}</span></div><h2>${esc(r.title)}</h2><p>${fmt(prepared.length)} 道准备题 · 含回答思路、模板与示范</p>${aliasText?`<p class="topic-aliases">合并：${esc(aliasText)}${r.aliases.length>3?` 等 ${r.aliases.length} 个标题`:''}</p>`:''}${tags([speakingThemeZh[r.primaryTheme]||r.primaryTheme,'练习优先'])}<button class="topic-open" data-topic-id="${esc(r.id)}" aria-expanded="false">展开练习 <span aria-hidden="true">＋</span></button></article>`}).join('')||'<p>没有匹配主题。</p>';
  $('#topic-grid').querySelectorAll('.topic-open').forEach(button=>button.onclick=()=>toggleInlineTopic(button.dataset.topicId,button));
  setupTopicHover();
  pager($('#topic-pages'),topicState.page,all.length,36,p=>{expandedTopicId='';activeTopicId='';topicState.page=p;renderTopics()});
}
function animateTopicLayout(update){
  const before=new Map($$('.topic').map(card=>[card.dataset.topicId,card.getBoundingClientRect()]));update();
  $$('.topic').forEach(card=>{const first=before.get(card.dataset.topicId);if(!first)return;const last=card.getBoundingClientRect();const dx=first.left-last.left;const dy=first.top-last.top;const sx=last.width?first.width/last.width:1;if(Math.abs(dx)<1&&Math.abs(dy)<1&&Math.abs(sx-1)<.01)return;card.style.transformOrigin='top left';card.style.transition='none';card.style.transform=`translate(${dx}px,${dy}px) scaleX(${sx})`;requestAnimationFrame(()=>{card.style.transition='transform 420ms cubic-bezier(.22,1,.36,1), border-color 180ms ease, box-shadow 180ms ease';card.style.transform='';setTimeout(()=>{card.style.removeProperty('transform-origin');card.style.removeProperty('transition');card.style.removeProperty('transform')},440)})});
}
function toggleInlineTopic(topicId,trigger){
  const topic=speakingData.topics.find(item=>item.id===topicId);if(!topic)return;
  const update=()=>{
    clearTopicHover();
    const previous=$('.topic.expanded');if(previous){previous.classList.remove('expanded');const previousButton=previous.querySelector('.topic-open');if(previousButton){previousButton.setAttribute('aria-expanded','false');previousButton.innerHTML='展开练习 <span aria-hidden="true">＋</span>'}previous.querySelector('.topic-inline-detail')?.remove()}
    if(expandedTopicId===topicId){expandedTopicId='';activeTopicId='';return}
    expandedTopicId=topicId;activeTopicId=topicId;dialogMode='practice';sourceViewState={part:topicState.part,current:topicState.current,q:'',limit:30};
    const card=trigger.closest('.topic');card.classList.add('expanded');trigger.setAttribute('aria-expanded','true');trigger.innerHTML='收起练习 <span aria-hidden="true">−</span>';
    card.insertAdjacentHTML('beforeend',`<section class="topic-inline-detail" aria-label="${esc(topic.title)} 学习内容"><div class="topic-inline-inner"><div class="inline-intro"><div><p class="eyebrow">Prepared practice first</p><h3>${esc(topicState.part||'全部 Part')} · ${esc(topic.titleZh)}</h3><p>先练习我们准备的问题与答案；需要核对题目出处时再打开“来源参考”。</p></div></div><div id="topic-dialog-mode" class="dialog-mode" aria-label="题目内容类型"></div><div id="question-list" class="question-list"></div></div></section>`);
    renderDialogMode();requestAnimationFrame(()=>card.querySelector('.topic-inline-detail')?.classList.add('ready'));setTimeout(()=>card.scrollIntoView({behavior:'smooth',block:'start'}),460);
  };
  animateTopicLayout(update);
}
function sourceGuide(part){
  if(part==='Part 1')return {ideas:['第一句直接回答，不要复述题目','补充一个真实的小例子或习惯','用 because 解释原因，控制在 2–4 句'],template:'I’d say ___. For example, ___. I feel this way mainly because ___.'};
  if(part==='Part 2')return {ideas:['按题卡提示覆盖人物、时间、地点和经过','用 before–during–after 形成清楚时间线','加入一个感官细节和一个转折','结尾解释它为何重要或难忘'],template:'I’d like to talk about ___. It happened when ___. At first, ___. Then ___. What I remember most is ___. Looking back, ___.'};
  return {ideas:['先给清楚立场或核心原因','解释因果，不只罗列观点','加入具体例子或群体比较','承认例外后给出平衡结论'],template:'I think the main reason is ___. This is because ___. A good example is ___. Admittedly, ___. Even so, ___.'};
}
function bindQuestionToggles(){
  $('#question-list').querySelectorAll('.question-toggle').forEach(button=>button.onclick=()=>{const panel=$(`#${CSS.escape(button.getAttribute('aria-controls'))}`);const expanded=button.getAttribute('aria-expanded')==='true';button.setAttribute('aria-expanded',String(!expanded));button.querySelector('.toggle-mark').textContent=expanded?'＋':'−';panel.hidden=expanded;});
}
function renderSourceQuestions(){
  const topic=speakingData.topics.find(item=>item.id===activeTopicId);if(!topic)return;
  const filtered=topic.questions.filter(question=>(!sourceViewState.part||question.part===sourceViewState.part)&&(!sourceViewState.current||question.current)&&(!sourceViewState.q||question.text.toLowerCase().includes(sourceViewState.q)||question.sourceRefs.some(ref=>{const source=speakingData.sources[ref];return source.name.toLowerCase().includes(sourceViewState.q)||source.region.toLowerCase().includes(sourceViewState.q)})));const rows=filtered.slice(0,sourceViewState.limit);
  const partControl=topicState.part?`<span class="part-lock">当前只看 ${esc(topicState.part)}</span>`:`<div id="source-part-tabs" class="tabs small">${[['','全部 Part'],['Part 1','Part 1'],['Part 2','Part 2'],['Part 3','Part 3']].map(([value,label])=>`<button class="${sourceViewState.part===value?'active':''}" data-value="${value}">${label}</button>`).join('')}</div>`;
  const controls=`<div class="source-controls">${partControl}<label class="check"><input id="source-current-only" type="checkbox" ${sourceViewState.current?'checked':''}> 只看 2026</label><form id="source-question-search" class="inline-search"><input value="${esc(sourceViewState.q)}" placeholder="搜索题目、来源或地区" aria-label="搜索来源题目"><button>搜索</button></form></div><p class="source-result-note">来源材料仅作核对参考；同文题目的多个来源已合并到同一条。</p>`;
  const list=rows.map((question,index)=>{const answerId=`source-answer-${esc(question.id)}`;const refs=question.sourceRefs.map(ref=>speakingData.sources[ref]);const guide=sourceGuide(question.part);return `<article class="question-item source-question"><button class="question-toggle" aria-expanded="false" aria-controls="${answerId}"><span class="question-number">${String(index+1).padStart(2,'0')}</span><span><small>${esc(question.part)}${question.current?' · 含 2026 来源':''}</small><b>${esc(question.text)}</b><em>${esc(refs[0]?.name||'来源未标注')}${refs.length>1?` ＋${refs.length-1} 个来源`:''}</em></span><span class="toggle-mark" aria-hidden="true">＋</span></button><div class="question-answer" id="${answerId}" hidden><section><h3>原始来源</h3><div class="source-citations">${refs.map(source=>`<div><span>${esc(groupZh[source.sourceGroup]||source.sourceGroup)}</span><p><b>${esc(source.name)}</b><small>${esc(source.period)} · ${esc(source.region)}</small></p>${source.url?`<a href="${safeUrl(source.url)}" target="_blank" rel="noreferrer">来源页 ↗</a>`:''}</div>`).join('')}</div></section><section><h3>回答思路</h3><ol>${guide.ideas.map(idea=>`<li>${esc(idea)}</li>`).join('')}</ol></section><section><h3>适用框架</h3><p class="answer-template">${esc(guide.template)}</p></section></div></article>`}).join('');
  const more=filtered.length>rows.length?`<button id="source-load-more" class="load-more">显示更多来源题</button>`:'';
  $('#question-list').innerHTML=controls+list+more||'<p>没有匹配的来源题目。</p>';
  $('#source-part-tabs')?.querySelectorAll('button').forEach(button=>button.onclick=()=>{sourceViewState.part=button.dataset.value;sourceViewState.limit=30;renderSourceQuestions()});
  $('#source-current-only').onchange=event=>{sourceViewState.current=event.target.checked;sourceViewState.limit=40;renderSourceQuestions()};
  $('#source-question-search').onsubmit=event=>{event.preventDefault();sourceViewState.q=event.target.querySelector('input').value.trim().toLowerCase();sourceViewState.limit=40;renderSourceQuestions()};
  $('#source-load-more')?.addEventListener('click',()=>{sourceViewState.limit+=40;renderSourceQuestions()});bindQuestionToggles();
}
function renderPracticeQuestions(){
  const practice=questionBank.topics[activeTopicId];if(!practice){$('#question-list').innerHTML='<p>该主题暂无本站练习。</p>';return}
  const prepared=practice.questions.filter(question=>!topicState.part||question.part===topicState.part);
  $('#question-list').innerHTML=`<p class="practice-note"><b>${esc(topicState.part||'全部 Part')} · ${esc(practice.contentLabel)}</b>　先练这些准备好的问题；每题都有思路、模板、示范回答和常用词。</p>`+prepared.map((question,index)=>{const answerId=`answer-${esc(question.id)}`;return `<article class="question-item"><button class="question-toggle" aria-expanded="false" aria-controls="${answerId}"><span class="question-number">${String(index+1).padStart(2,'0')}</span><span><small>${esc(question.part)}</small><b>${esc(question.question)}</b></span><span class="toggle-mark" aria-hidden="true">＋</span></button><div class="question-answer" id="${answerId}" hidden><section><h3>回答思路</h3><ol>${question.ideasZh.map(idea=>`<li>${esc(idea)}</li>`).join('')}</ol></section><section><h3>可替换模板</h3><p class="answer-template">${esc(question.templateEn)}</p></section><section><h3>示范回答</h3><p class="sample-answer" lang="en">${esc(question.sampleAnswerEn)}</p></section><section><h3>本题常用词</h3><div class="vocab-list">${question.vocabulary.map(item=>`<span><b>${esc(item.word)}</b>${esc(item.meaningZh)}</span>`).join('')}</div></section></div></article>`}).join('');bindQuestionToggles();
}
function renderDialogMode(){
  const topic=speakingData.topics.find(item=>item.id===activeTopicId);const practice=questionBank.topics[activeTopicId];
  const prepared=(practice?.questions||[]).filter(question=>!topicState.part||question.part===topicState.part);
  $('#topic-dialog-mode').innerHTML=`<button class="${dialogMode==='practice'?'active':''}" data-mode="practice">准备的问题与示范 <b>${fmt(prepared.length)}</b></button><button class="${dialogMode==='source'?'active':''}" data-mode="source">来源参考</button>`;
  $('#topic-dialog-mode').querySelectorAll('button').forEach(button=>button.onclick=()=>{dialogMode=button.dataset.mode;renderDialogMode()});
  if(dialogMode==='source')renderSourceQuestions();else renderPracticeQuestions();
}
const writingPalette=['#0e6655','#d89435','#58758a','#9b6b5e'];
function chartLegend(series){return `<div class="chart-legend">${series.map((item,index)=>`<span><i class="chart-swatch-${index%writingPalette.length}"></i>${esc(item.name||item.label)}</span>`).join('')}</div>`}
function chartTicks(max){const top=Math.max(10,Math.ceil(max/10)*10);return {top,values:[0,top/2,top]}}
function renderLineChart(visual){
  const width=760,height=330,left=72,right=28,top=55,bottom=60,plotWidth=width-left-right,plotHeight=height-top-bottom;const values=visual.series.flatMap(series=>series.values);const scale=chartTicks(Math.max(...values));const x=index=>left+(visual.labels.length===1?plotWidth/2:index*plotWidth/(visual.labels.length-1));const y=value=>top+plotHeight-(value/scale.top)*plotHeight;
  return `<div class="chart-frame"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(visual.title)}"><title>${esc(visual.title)}</title><text x="${left}" y="24" class="chart-title">${esc(visual.title)}</text><text x="${left}" y="43" class="chart-unit">${esc(visual.unit)}</text>${scale.values.map(value=>`<g><line x1="${left}" x2="${width-right}" y1="${y(value)}" y2="${y(value)}" class="chart-gridline"/><text x="${left-12}" y="${y(value)+4}" text-anchor="end" class="chart-label">${value}</text></g>`).join('')}${visual.labels.map((label,index)=>`<text x="${x(index)}" y="${height-26}" text-anchor="middle" class="chart-label">${esc(label)}</text>`).join('')}${visual.series.map((series,index)=>{const points=series.values.map((value,i)=>`${x(i)},${y(value)}`).join(' ');return `<polyline points="${points}" fill="none" stroke="${writingPalette[index%writingPalette.length]}" stroke-width="5" stroke-linejoin="round" stroke-linecap="round"/>${series.values.map((value,i)=>`<circle cx="${x(i)}" cy="${y(value)}" r="5" fill="${writingPalette[index%writingPalette.length]}"/><text x="${x(i)}" y="${y(value)-12}" text-anchor="middle" class="chart-value">${value}</text>`).join('')}`}).join('')}</svg>${chartLegend(visual.series)}</div>`;
}
function renderBarChart(visual){
  const width=760,height=340,left=72,right=24,top=58,bottom=76,plotWidth=width-left-right,plotHeight=height-top-bottom;const values=visual.series.flatMap(series=>series.values);const scale=chartTicks(Math.max(...values));const y=value=>top+plotHeight-(value/scale.top)*plotHeight;const groupWidth=plotWidth/visual.labels.length;const barWidth=Math.min(42,(groupWidth-28)/visual.series.length);
  return `<div class="chart-frame"><svg viewBox="0 0 ${width} ${height}" role="img" aria-label="${esc(visual.title)}"><title>${esc(visual.title)}</title><text x="${left}" y="25" class="chart-title">${esc(visual.title)}</text><text x="${left}" y="44" class="chart-unit">${esc(visual.unit)}</text>${scale.values.map(value=>`<g><line x1="${left}" x2="${width-right}" y1="${y(value)}" y2="${y(value)}" class="chart-gridline"/><text x="${left-12}" y="${y(value)+4}" text-anchor="end" class="chart-label">${value}</text></g>`).join('')}${visual.labels.map((label,group)=>{const start=left+group*groupWidth+(groupWidth-barWidth*visual.series.length)/2;return `${visual.series.map((series,index)=>{const value=series.values[group];const barX=start+index*barWidth;return `<rect x="${barX}" y="${y(value)}" width="${barWidth-5}" height="${top+plotHeight-y(value)}" rx="3" fill="${writingPalette[index%writingPalette.length]}"/><text x="${barX+(barWidth-5)/2}" y="${y(value)-8}" text-anchor="middle" class="chart-value">${value}</text>`}).join('')}<text x="${left+group*groupWidth+groupWidth/2}" y="${height-34}" text-anchor="middle" class="chart-label">${esc(label)}</text>`}).join('')}</svg>${chartLegend(visual.series)}</div>`;
}
function renderPieCharts(visual){
  const segments=visual.panels[0].segments;return `<div class="pie-visual"><h4>${esc(visual.title)}</h4><div class="pie-panels">${visual.panels.map(panel=>{let offset=0;const arcs=panel.segments.map((segment,index)=>{const arc=`<circle cx="90" cy="90" r="66" fill="none" stroke="${writingPalette[index%writingPalette.length]}" stroke-width="42" pathLength="100" stroke-dasharray="${segment.value} ${100-segment.value}" stroke-dashoffset="-${offset}" transform="rotate(-90 90 90)"/>`;offset+=segment.value;return arc}).join('');return `<div class="pie"><svg viewBox="0 0 180 180" role="img" aria-label="${esc(panel.title)}"><title>${esc(panel.title)}</title>${arcs}<circle cx="90" cy="90" r="42" fill="#fff"/><text x="90" y="96" text-anchor="middle">${esc(panel.title)}</text></svg></div>`}).join('')}</div>${chartLegend(segments)}<div class="pie-values">${visual.panels.map(panel=>`<p><b>${esc(panel.title)}</b>${panel.segments.map(segment=>`<span>${esc(segment.label)} ${segment.value}%</span>`).join('')}</p>`).join('')}</div></div>`;
}
function renderTableVisual(visual){return `<div class="writing-table-visual"><h4>${esc(visual.title)}</h4><div><table><thead><tr>${visual.headers.map(header=>`<th>${esc(header)}</th>`).join('')}</tr></thead><tbody>${visual.rows.map(row=>`<tr>${row.map((cell,index)=>`<${index?'td':'th'}>${esc(cell)}</${index?'td':'th'}>`).join('')}</tr>`).join('')}</tbody></table></div></div>`}
function renderMapVisual(visual){return `<div class="map-visual"><h4>${esc(visual.title)}</h4><div class="map-panels">${visual.panels.map(panel=>`<section><h5>${esc(panel.title)}</h5><div class="map-grid">${panel.grid.flat().map(cell=>`<span>${esc(cell)}</span>`).join('')}</div></section>`).join('')}</div><p class="map-north">↑ North</p></div>`}
function renderFlowVisual(visual,system=false){return `<div class="flow-visual"><h4>${esc(visual.title)}</h4><div class="flow-stages">${visual.stages.map((stage,index)=>`<span>${esc(stage)}${index<visual.stages.length-1?'<i aria-hidden="true">→</i>':''}</span>`).join('')}</div>${system?`<div class="flow-outputs"><b>Reuse / overflow</b>${visual.outputs.map(output=>`<span>${esc(output)}</span>`).join('')}</div>`:''}</div>`}
function renderMixedVisual(visual){return `<div class="mixed-visual"><h4>${esc(visual.title)}</h4><div>${renderBarChart({title:visual.bars.name,unit:visual.bars.unit,labels:visual.labels,series:[{name:visual.bars.name,values:visual.bars.values}]})}${renderLineChart({title:visual.line.name,unit:visual.line.unit,labels:visual.labels,series:[{name:visual.line.name,values:visual.line.values}]})}</div></div>`}
function renderWritingVisual(visual){if(!visual)return '';if(visual.type==='line')return renderLineChart(visual);if(visual.type==='bar')return renderBarChart(visual);if(visual.type==='pie')return renderPieCharts(visual);if(visual.type==='table')return renderTableVisual(visual);if(visual.type==='map')return renderMapVisual(visual);if(visual.type==='process')return renderFlowVisual(visual);if(visual.type==='system')return renderFlowVisual(visual,true);if(visual.type==='mixed')return renderMixedVisual(visual);return ''}
function writingWordCount(item){return item.modelAnswer.join(' ').trim().split(/\s+/).filter(Boolean).length}
function writingModeContent(item){
  if(writingState.mode==='language')return `<section class="writing-study-section"><p class="eyebrow">Reusable language</p><h4>可替换框架</h4><ol class="writing-template-list">${item.templateEn.map(line=>`<li lang="en">${esc(line)}</li>`).join('')}</ol><h4>本题常用词</h4><div class="vocab-list writing-vocab">${item.vocabulary.map(entry=>`<span><b>${esc(entry.word)}</b>${esc(entry.meaningZh)}</span>`).join('')}</div></section>`;
  if(writingState.mode==='sample')return `<section class="writing-study-section"><div class="writing-sample-head"><div><p class="eyebrow">Original model response</p><h4>本站原创范文</h4></div><span>${writingWordCount(item)} words</span></div><p class="writing-boundary">这是结构与语言学习样例，不是 IELTS 官方范文，也不代表官方定档分数。请先独立写作，再对照修改。</p><div class="writing-sample" lang="en">${item.modelAnswer.map(paragraph=>`<p>${esc(paragraph)}</p>`).join('')}</div></section>`;
  if(writingState.mode==='review')return `<section class="writing-study-section"><p class="eyebrow">Four-criterion check</p><h4>按官方四维度自检</h4><div class="writing-criteria-check">${writingBank.criteria.map(criterion=>`<article><span>${esc(item.task==='Task 1'?criterion.officialTask1:criterion.officialTask2)}</span><h5>${esc(criterion.titleZh)}</h5><p>${esc(item.criterionNotes[criterion.id])}</p></article>`).join('')}</div></section>`;
  return `<section class="writing-study-section"><p class="eyebrow">Plan before writing</p><h4>${item.task==='Task 1'?'主要特征与概览':'中心立场与回应'}</h4><p class="writing-overview">${esc(item.overviewZh)}</p><div class="writing-plan">${item.plan.map((step,index)=>`<article><span>${String(index+1).padStart(2,'0')}</span><div><h5>${esc(step.headingZh)}</h5><p>${esc(step.contentZh)}</p></div></article>`).join('')}</div></section>`;
}
function renderWritingDetail(item){return `<section class="writing-inline-detail ready" aria-label="${esc(item.titleZh)} 学习内容"><div class="writing-prompt"><div><span>${esc(item.task)} · ${item.timeMinutes} 分钟 · 至少 ${item.minimumWords} 词</span><b>本站原创练习</b></div><p lang="en">${esc(item.question)}</p></div>${renderWritingVisual(item.visual)}<p class="writing-visual-note">${item.visual?'题目数据与图示由本站原创构造，仅用于练习。':''}</p><div class="writing-mode" aria-label="写作学习内容">${[['analysis','审题与结构'],['language','词汇与模板'],['sample','原创范文'],['review','四项自检']].map(([value,label])=>`<button class="${writingState.mode===value?'active':''}" data-writing-mode="${value}">${label}</button>`).join('')}</div><div class="writing-mode-content">${writingModeContent(item)}</div></section>`}
function renderWritingExercises(){
  const grid=$('#writing-exercise-grid');const rows=writingBank.exercises.filter(item=>item.task===writingState.task);grid.innerHTML=rows.map(item=>{const expanded=item.id===writingState.expanded;return `<article class="writing-exercise-card ${expanded?'expanded':''}" data-writing-id="${esc(item.id)}"><div class="writing-card-summary"><div class="topic-meta"><span>${esc(labelZh[item.type]||item.type)}</span><span>${item.timeMinutes} min</span></div><h3>${esc(item.titleZh)}</h3><p>${esc(item.question)}</p>${tags([labelZh[item.topic]||item.topic,item.visual?'含原创图示':'原创议论文'])}<button class="writing-open" data-writing-id="${esc(item.id)}" aria-expanded="${expanded}">${expanded?'收起内容':'查看题目与范文'} <span aria-hidden="true">${expanded?'−':'＋'}</span></button></div>${expanded?renderWritingDetail(item):''}</article>`}).join('');
  grid.querySelectorAll('.writing-open').forEach(button=>button.onclick=()=>{const closing=writingState.expanded===button.dataset.writingId;writingState.expanded=closing?'':button.dataset.writingId;writingState.mode='analysis';renderWritingExercises();if(!closing)setTimeout(()=>grid.querySelector(`[data-writing-id="${CSS.escape(writingState.expanded)}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}),120)});
  grid.querySelectorAll('[data-writing-mode]').forEach(button=>button.onclick=()=>{writingState.mode=button.dataset.writingMode;renderWritingExercises()});
}
function facet(task,type,scope,limit=10){return `<div class="facet">${data.writingFacets.filter(r=>r.task===task&&r.facetType===type&&r.scope===scope).slice(0,limit).map(r=>`<div><span>${esc(labelZh[r.label]||r.label)}</span><strong>${fmt(r.count)}</strong><small>${r.sourceCount} 个来源集合</small></div>`).join('')}</div>`}
function renderWriting(){
  const block=(title,scope,type)=>`<section class="writing-section"><div class="section-head"><div><p class="eyebrow">${scope==='recent_3y'?'Recent 3 years':'Corpus categories'}</p><h2>${title}</h2></div></div><div class="panel-grid"><article class="panel"><h3>Task 1</h3>${facet('Task 1',type,scope)}</article><article class="panel"><h3>Task 2</h3>${facet('Task 2',type,scope)}</article></div></section>`;
  $('#writing-content').innerHTML=`<section class="writing-guide"><div><p class="eyebrow">Official format · original practice</p><h2>先学怎么回应，再看范文</h2><p>${esc(writingBank.meta.copyrightNoteZh)}</p></div><div class="writing-criteria-summary">${writingBank.criteria.map(criterion=>`<article><b>${esc(criterion.titleZh)}</b><span>${esc(criterion.descriptionZh)}</span></article>`).join('')}</div><div class="writing-references">${writingBank.meta.referenceSources.map(source=>`<a href="${safeUrl(source.url)}" target="_blank" rel="noreferrer"><span>${esc(source.publisher)}</span>${esc(source.name)} ↗</a>`).join('')}</div></section><section class="writing-practice"><div class="section-head"><div><p class="eyebrow">Question → plan → language → model</p><h2>题目与原创范文</h2></div><p>Task 1 包含本站原创图表、表格、地图和流程图；Task 2 覆盖当前语料中的六种主要问法。点击题型后原地展开。</p></div><div id="writing-task-tabs" class="tabs writing-task-tabs"></div><div id="writing-exercise-grid" class="writing-exercise-grid"></div></section><section class="writing-statistics"><div class="section-head"><div><p class="eyebrow">Corpus evidence</p><h2>题型与主题统计</h2></div><p>统计和学习内容分开：次数来自语料，练习与范文为本站原创。</p></div>${block('大小作文题型','overall','task_type')+block('总体常见主题','overall','theme')+block('2024–2026 常见主题','recent_3y','theme')}</section>`;
  buttonTabs($('#writing-task-tabs'),[['Task 1','Task 1 小作文'],['Task 2','Task 2 大作文']],writingState.task,value=>{writingState.task=value;writingState.expanded='';writingState.mode='analysis';renderWriting()});renderWritingExercises();
}
function renderChunks(){
  const stat=chunkBank.skillStats.find(item=>item.skill===chunkState.skill);if(!stat)return;
  const categories=['全部',...stat.categories.map(item=>item.name)];if(!categories.includes(chunkState.category))chunkState.category='全部';
  buttonTabs($('#chunk-skill-tabs'),[['Reading','阅读词块'],['Listening','听力词块']],chunkState.skill,value=>{chunkState.skill=value;chunkState.category='全部';chunkState.expanded='';renderChunks()});
  buttonTabs($('#chunk-category-tabs'),categories.map(value=>[value,value]),chunkState.category,value=>{chunkState.category=value;chunkState.expanded='';renderChunks()});
  const rows=chunkBank.chunks.filter(item=>item.skill===chunkState.skill&&(chunkState.category==='全部'||item.category===chunkState.category));
  $('#chunk-method').textContent=`${chunkBank.methodology.countUnitZh} ${chunkBank.methodology.confidenceZh}`;
  $('#chunk-summary').innerHTML=`<p><b>${skillZh[stat.skill]} · ${fmt(rows.length)} 个词块</b><span>统计底座：${fmt(stat.documents)} 个去重统计单元 · ${fmt(stat.filteredTokenCount)} 个学习词 token · ${fmt(stat.sourceCount)} 个来源集合</span></p><p>${esc(chunkBank.meta.copyrightNoteZh)}</p>`;
  $('#chunk-grid').innerHTML=rows.map((item,index)=>{const expanded=item.id===chunkState.expanded;return `<article class="chunk-card ${expanded?'expanded':''}" data-chunk-id="${esc(item.id)}"><button class="chunk-toggle" data-chunk-id="${esc(item.id)}" aria-expanded="${expanded}"><span class="chunk-rank">${String(index+1).padStart(2,'0')} · ${esc(item.category)}</span><strong lang="en">${esc(item.phrase)}</strong><span>${esc(item.meaningZh)}</span><div class="chunk-evidence"><b>${fmt(item.occurrenceCount)}<small>出现</small></b><b>${fmt(item.documentFrequency)}<small>文档</small></b><b>${(item.documentCoverage*100).toFixed(1)}%<small>覆盖</small></b><b>${fmt(item.sourceCount)}<small>来源</small></b><em class="badge ${esc(item.confidence)}">${esc(confidenceZh[item.confidence])}</em></div><i aria-hidden="true">${expanded?'−':'＋'}</i></button>${expanded?`<div class="chunk-detail"><section><small>搭配骨架</small><p class="chunk-frame" lang="en">${esc(item.frame)}</p></section><section><small>使用提示</small><p>${esc(item.usageZh)}</p></section><section class="chunk-example"><small>${esc(item.contentLabel)}</small><blockquote lang="en">${esc(item.exampleEn)}</blockquote><p>${esc(item.exampleZh)}</p></section></div>`:''}</article>`}).join('');
  $('#chunk-grid').querySelectorAll('.chunk-toggle').forEach(button=>button.onclick=()=>{const closing=chunkState.expanded===button.dataset.chunkId;chunkState.expanded=closing?'':button.dataset.chunkId;renderChunks();if(!closing)setTimeout(()=>$('#chunk-grid').querySelector(`[data-chunk-id="${CSS.escape(chunkState.expanded)}"]`)?.scrollIntoView({behavior:'smooth',block:'center'}),80)});
}
function renderCoverage(){const rows=data.coverage.filter(r=>['Listening','Reading'].includes(r.skill));$('#lr-coverage').innerHTML=rows.map(r=>`<article class="metric"><p class="eyebrow">${r.skill}</p><strong>${fmt(r.documents)}</strong><h3>${skillZh[r.skill]}去重统计单元</h3><p>${fmt(r.filteredTokens)} 个学习词 token · ${r.sources} 个来源集合</p>${tags(r.sourceGroups)}</article>`).join('');renderChunks()}
function renderSources(){const sources=[...data.sources].sort((a,b)=>b.reliabilityWeight-a.reliabilityWeight||b.documentCount-a.documentCount);$('#source-list').innerHTML=sources.map(s=>`<article class="source"><div><span class="grade">${Math.round(s.reliabilityWeight*100)}%</span></div><div><p class="eyebrow">${esc(groupZh[s.sourceGroup]||s.sourceGroup)}</p><h2>${esc(s.name)}</h2><p>${esc(s.notes)}</p>${tags([s.skill,s.period||'时期未标注',s.publicDisplay])}</div><div class="numbers"><b>${fmt(s.documentCount)}</b><small>统计单元</small><b>${fmt(s.wordCount)}</b><small>学习词 token</small>${s.url?`<a href="${safeUrl(s.url)}" target="_blank" rel="noreferrer">原始来源 ↗</a>`:''}</div></article>`).join('')}
async function boot(){try{const manifestRes=await fetch(`data/manifest.json?t=${Date.now()}`,{cache:'no-store'});if(!manifestRes.ok)throw new Error('manifest');manifest=await manifestRes.json();const version=encodeURIComponent(manifest.dataVersion);const [corpusRes,speakingRes,questionsRes,writingRes,chunksRes]=await Promise.all([fetch(`${manifest.files.corpus}?v=${version}`,{cache:'no-cache'}),fetch(`${manifest.files.speaking}?v=${version}`,{cache:'no-cache'}),fetch(`${manifest.files.questions}?v=${version}`,{cache:'no-cache'}),fetch(`${manifest.files.writing}?v=${version}`,{cache:'no-cache'}),fetch(`${manifest.files.chunks}?v=${version}`,{cache:'no-cache'})]);if(!corpusRes.ok||!speakingRes.ok||!questionsRes.ok||!writingRes.ok||!chunksRes.ok)throw new Error('data');[data,speakingData,questionBank,writingBank,chunkBank]=await Promise.all([corpusRes.json(),speakingRes.json(),questionsRes.json(),writingRes.json(),chunksRes.json()]);const updated=new Date(manifest.generatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});$('#data-status').textContent=`在线数据 ${manifest.dataVersion}`;$('#data-version').innerHTML=`当前公开数据库版本：<b>${esc(manifest.dataVersion)}</b> · 北京时间 ${esc(updated)} · ${fmt(manifest.counts.topics)} 个合并主题 · ${fmt(manifest.counts.practiceQuestions)} 道口语问答 · ${fmt(manifest.counts.writingExercises)} 篇写作练习。<a href="${safeUrl(manifest.repository)}/tree/main/data" target="_blank" rel="noreferrer">查看 GitHub 数据文件 ↗</a>`;renderHome();renderWords();renderTopics();renderWriting();renderCoverage();renderSources();showView();addEventListener('hashchange',showView);$('#loading').classList.add('done')}catch(e){console.error(e);$('#loading').textContent='数据载入失败，请刷新页面。'}}
boot();
